services:
  ros2_ur5e:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: ros2_ur5e_container
    network_mode: host
    ipc: host
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=0
    volumes:
      - .:/ros2_ws/src/hand_pattern_recognition
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev/dri:/dev/dri:rw
    devices:
      - /dev/video0:/dev/video0
    privileged: true
    stdin_open: true
    tty: true
    command: bash -c "colcon build && source install/setup.bash && ros2 launch ur5e_desk_bringup bringup.launch.py"
